- name:  Change hostname
  hosts: all
  gather_facts: false
  collections:
    - ansible.windows
  tasks:
       
    - name: Change the hostname to sample-hostname
      ansible.windows.win_hostname:
        name: sample-hostname
      register: res

    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required
