- name:  Install Terminal Server
  hosts: all
  gather_facts: false
  tasks:
    
    - name: Set timezone to Russian Standard Time (GMT+03:00)
      win_timezone:
        timezone: Russian Standard Time
      
    - name: Change the hostname to sample-hostname
      win_hostname:
        name: termdev1c
      register: res

    - name: Reboot
      win_reboot:
      when: res.reboot_required