- name:  Enable Remote Desktop Protocol
  hosts: all
  gather_facts: false
  tasks:
    - name: Run PowerShell command
      win_regedit:
        path: HKLM:\System\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections 
        data: 0
