- name:  Enable Remote Desktop Protocol
  hosts: all
  gather_facts: false
  tasks:
    - name: Run PowerShell command
      win_shell: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
