---
- hosts: all
  tasks:

  - name: Run PowerShell command
    win_shell: Set-Content -Path C:\temp\test.txt -Value 'Hello World'

  - name: Run multi-lined shell commands
    win_shell: |
        $text = Get-Content C:\Temp\test.txt
        $text += ' additional text'
        Set-Content -Path C:\Temp\test2.txt -Value $text
        
  - name: Win copy
    win_copy:
      src: \\dc01.shliss.ru\folder\file\test.ps1
      dest: c:\temp\
      remote_src: True
      become: yes
      become_method: runas
      become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      vars:
        ansible_become_user: SHLISS\adminDC
        ansible_become_pass: QQQ111www222
        
     
  - name: Run a script
    win_shell: C:\temp\test.ps1
