---
- hosts: all
  tasks:

  - name: Run PowerShell command
    win_shell: Set-Content -Path C:\temp\test.txt -Value 'Hello World'

  - name: Run multi-lined shell commands
    win_shell: |
        $text = Get-Content C:\Temp\test.txt
        $text += ' additional text'
        Set-Content -Path C:\Temp\test2.txt -Value $text

  - name: Copy a single file
    win_shell:
      $Destination = "c:\temp"
      $Source = "\\dc01.shliss.ru\folder\files\test.ps1"
      Copy-Item -Path $Source -Destination $Destination -Force

  - name: Run a script
    win_shell: C:\temp\test.ps1
