---
- hosts: all
  tasks:

  - name: Run PowerShell command
    win_shell: Set-Content -Path C:\temp\test.txt -Value 'Hello World'

  - name: Run multi-lined shell commands
    win_shell: |
        $text = Get-Content C:\Temp\test.txt
        $text += ' additional text'
        Set-Content -Path C:\Temp\test2.txt -Value $text
        
  - name: Create a mapped drive under Z
    win_mapped_drive:
      letter: Z
      path: \\dc01.shliss.ru\folder
      username: SHLISS\adminDC
      password: QQQ111www222
  
  - name: Copy a single file
    win_shell: copy Z:  c:\temp     
      
  - name: Run a script
    win_shell: C:\temp\test.ps1
