---
#Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- name:  Windows Update
  hosts: all
  gather_facts: false
  tasks:
    - name: Restart a service
      win_service:
        name: spooler
        state: restarted

    - name: Set service startup mode to auto and ensure it is started
      win_service:
         name: spooler
         start_mode: auto
         state: started

     # reboot only if required
 #   - win_reboot:
  #    when: result.reboot_required
